CREATE TABLE `Untitled2` (
	`Key`	BIGINT	NOT NULL,
	`Field2`	VARCHAR	NULL,
	`Field3`	VARCHAR	NULL,
	`Field4`	VARCHAR	NULL,
	`Field5`	VARCHAR	NULL,
	`Field6`	VARCHAR	NULL,
	`Field7`	TIME	NULL,
	`Field8`	TIME	NULL,
	`Field9`	VARCHAR	NULL,
	`Key2`	VARCHAR	NOT NULL
);

CREATE TABLE `Untitled4` (
	`Key`	BIGINT	NOT NULL,
	`Field2`	VARCHAR	NULL,
	`Field3`	INT	NULL,
	`Field4`	VARCHAR	NULL,
	`Field5`	TIME	NULL,
	`Field6`	TIME	NULL,
	`Field7`	BOOLEAN	NULL,
	`Key2`	BIGINT	NOT NULL
);

CREATE TABLE `Untitled6` (
	`Key`	BIGINT	NOT NULL,
	`Key2`	BIGINT	NOT NULL,
	`Key3`	BIGINT	NOT NULL
);

CREATE TABLE `Untitled3` (
	`Key`	BIGINT	NOT NULL,
	`Field`	VARCHAR	NULL,
	`Field2`	VARCHAR	NULL,
	`Field3`	VARCHAR	NULL
);

CREATE TABLE `Untitled8` (
	`Key`	BIGINT	NOT NULL,
	`Key2`	BIGINT	NOT NULL,
	`Key3`	BIGINT	NOT NULL
);

CREATE TABLE `Untitled9` (
	`Key`	VARCHAR	NOT NULL,
	`Field`	VARCHAR	NULL,
	`Field2`	VARCHAR	NULL
);

CREATE TABLE `Untitled5` (
	`Key`	BIGINT	NOT NULL,
	`Field2`	INT	NULL,
	`Key2`	BIGINT	NOT NULL
);

CREATE TABLE `Untitled` (
	`Key`	VARCHAR	NOT NULL,
	`Field`	VARCHAR	NULL,
	`Field2`	VARCHAR	NULL,
	`Field3`	INT	NULL,
	`Key2`	VARCHAR	NOT NULL
);

CREATE TABLE `Untitled7` (
	`Key`	BIGINT	NOT NULL,
	`Field2`	VARCHAR	NULL,
	`Field3`	DATETIME	NULL,
	`Key2`	BIGINT	NOT NULL
);

ALTER TABLE `Untitled2` ADD CONSTRAINT `PK_UNTITLED2` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled4` ADD CONSTRAINT `PK_UNTITLED4` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled6` ADD CONSTRAINT `PK_UNTITLED6` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled3` ADD CONSTRAINT `PK_UNTITLED3` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled8` ADD CONSTRAINT `PK_UNTITLED8` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled9` ADD CONSTRAINT `PK_UNTITLED9` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled5` ADD CONSTRAINT `PK_UNTITLED5` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled` ADD CONSTRAINT `PK_UNTITLED` PRIMARY KEY (
	`Key`
);

ALTER TABLE `Untitled7` ADD CONSTRAINT `PK_UNTITLED7` PRIMARY KEY (
	`Key`
);

